# this action goes in www-project-cheat-sheets
# when CheatSheetsSeries updates this action will get called
name: CheatSheets Update
on:
  repository_dispatch:
    branches: [ master ]

jobs:
    update:
        runs-on: [ubuntu-latest]
        
        steps:
          - uses: actions/checkout@v2
          - name: Setup Python 3.7
            uses: actions/setup-python@v1
            with:
              python-version: '3.7' # Semantic version range syntax or exact version of a Python version
          - name: Update this repo with items from remote repo
            run: |
              # change this to clone the CheatSheetSeries repository
              git clone https://github.com/owasp/test-cs-storage ~/test-cs-storage
              # remove local cheatsheets
              rm -r cheatsheets/*
              # copy the cheetsheets from CheatSheetSeries
              # TODO: change the folder to match the git clone
              cp -r ~/test-cs-storage/cheatsheets .
              # update_files.py should reside in www-project-cheat-sheets
              # the script adds the front matter to each cheat sheet
              python update_files.py
              # commit and push the files to the www-project-cheat-sheets repo
              # TODO: change the repo on the push and update the user and email if you prefer
              # TODO: make sure to set up your github tokens
              git add cheatsheets
              git config --global user.name 'Harold Blankenship'
              git config --global user.email 'hblankenship@owasp.com'
              git commit -m "Automatic publish from github.com/owasp/test-cs-storage"
              git push https://github.com/owasp/www-test-cs-pull master
              
