# when test-cs-storage updates this action gets called
name: CheatSheets Update
on:
  repository_dispatch:
    branches: [ master ]

jobs:
    update:
        runs-on: [ubuntu-latest]
        
        steps:
          - uses: actions/checkout@v2
          - name: Update this repo with items from remote repo
            run: |
              echo "Git Clone" 
              git clone https://github.com/owasp/test-cs-storage 
              echo "rm...what is this and why"
              rm -r www-test-cs-pull/cheatsheets/*
              echo "copy"
              copy -r test-cs-storage/cheatsheets www-test-cs-pull
              echo "git add commit and push"
              git add www-test-cs-pull/cheatsheets
              git commit -m "Automatic publish from github.com/owasp/test-cs-storage"
              git push www-test-cs-pull master
