# This is a basic workflow to help you get started with Actions

name: CheatSheets Update
on:
  repository_dispatch:
    branches: [ master ]

jobs:
    update:
        runs-on: [ubuntu-latest]
        
        steps:
            - name: Update this repo with items from remote repo
        run: |
            git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/owasp/CheatSheetSeries www-test-cs-pull
            rm www-test-cs-pull
            copy CheatSheetSeries\cheatsheets www-test-cs-pull
            git add www-test-cs-pull
            git commit -m "Automatic publish from github.com/owasp/CheatSheetSeries"
            git push www-test-cs-pull master
