# when test-cs-storage updates this action gets called
name: CheatSheets Update
on:
  repository_dispatch:
    branches: [ master ]

jobs:
    update:
        runs-on: [ubuntu-latest]
        
        steps:
          - uses: actions/checkout@v2
          - name: Setup Python 3.7
            uses: actions/setup-python@v1
            with:
              python-version: '3.7' # Semantic version range syntax or exact version of a Python version
          - name: Update this repo with items from remote repo
            run: |
              echo "Git Clone" 
              git clone https://github.com/owasp/test-cs-storage ~/test-cs-storage
              echo "rm...what is this and why"
              rm -r cheatsheets/*
              echo "copy"
              cp -r ~/test-cs-storage/cheatsheets .
              python update_files.py
              echo "git add commit and push"
              git add cheatsheets
              git config --global user.name 'Harold Blankenship'
              git config --global user.email 'hblankenship@owasp.com'
              git commit -m "Automatic publish from github.com/owasp/test-cs-storage"
              git push https://github.com/owasp/www-test-cs-pull master
              
